### ISSUE TITLE
Request body checking does not work

### ISSUE THREAD

**Issue by ShiMing-Q** [jptosso/coraza-server#1]
## Description

Request body checking does not work because request body is always empty.

### Code with issues

File, `protocols/spoa/request_processor.go`
Line 25, `value, ok = arg.Value.(string)`

The `arg.Value` is not string for request body, however it's `[]byte`

### Steps to reproduce

Send a request and check the request body

### Expected result

The request body could be checked.

CRS rule id 921110 could be matched by send below request
`curl -X POST http://localhost:8888/ -d "var=%0aPOST / HTTP/1.0" -H 'Content-Type: text/plain'`

### Actual result

Request body check does not work.

**Comment by jptosso** [comment]
Hey, I will run some tests on this and upgrade coraza-server to the latest Coraza version. Have you confirmed that asserting arg.Value to []byte works? Also have you confirmed that the body is being sent from haproxy? 

Could you share your HAProxy settings?

**Comment by ShiMing-Q** [comment]
Yes I am running against haproxy. Please see below pic, I debugged the code
![image](https://user-images.githubusercontent.com/10385477/148559280-dcb28443-519f-4dc2-9169-22cc7eb2d2ba.png)

Settings
----------------------------------------------------------------------
haproxy.cfg

```
global
    log stdout format raw local0
defaults
    timeout connect 5s
    timeout client 1m
    timeout server 1m
    log global
frontend testsite.com
    unique-id-format %[uuid()]
    bind 0.0.0.0:8888
    mode http
    filter spoe engine coraza-waf config /usr/local/etc/haproxy/coraza.cfg
    http-request deny if { var(txn.coraza.fail) -m int eq 1 }
    http-response deny if { var(txn.coraza.fail) -m int eq 1 }
    use_backend test_backend
backend test_backend
    balance roundrobin
    mode http
    server s1 ppaas31.fyre.com:9001
    server s2 ppaas31.fyre.com:9001
backend coraza-servers
    mode tcp
    server coraza-spoa1 host.docker.internal:9000
```

coraza.cfg

```
[coraza-waf]
spoe-agent coraza-agent
    messages coraza-req coraza-res
    option var-prefix coraza
    timeout hello 2s
    timeout idle  2m
    timeout processing 10ms
    use-backend coraza-servers
    log global
spoe-message coraza-req
    args unique-id src method path query req.ver req.hdrs req.body_size req.body
    event on-frontend-http-request
spoe-message coraza-res
    args unique-id status res.ver res.hdrs res.body_size res.body
    event on-http-response
```

**Comment by jptosso** [comment]
Could you try https://github.com/jptosso/coraza-server/tree/fix-bodies ? I switched strings to []byte and added transaction cleaning support.

**Comment by ShiMing-Q** [comment]
Branch `fix-bodies`
File `protocols/spoa/request_processor.go`
Line `82`
Should be `tx.RequestBodyBuffer.Write(body)`

**Comment by jptosso** [comment]
My misstake, fixed now

**Comment by ShiMing-Q** [comment]
Works now.

**Comment by jptosso** [comment]
Great to hear, closing issue!
